apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-team
  namespace: argocd

spec:
  description: this project holds a new frontend app
  sourceRepos:
    - https://github.com/Akash-Verma-11/argocd-demos.git
  destinations:
    - namespace: frontend
      server: https://172.31.6.204:33893
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*" 
  roles:
    - name: frontend-admins
      description: Admins for frontend team
      policies:
        - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow
